name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  smoke:
    uses: ./.github/workflows/smoke.yml

  build:
    needs: smoke
    permissions:
      contents: write
      packages: write
    uses: actionsforge/actions/.github/workflows/docker-image-release.yml@main
    secrets: inherit
